variables:
  DEV_SSH: ssh root@139.59.252.24
stages:
  - release
  - deploy

dev-deploy:
  stage: deploy
  image: twinsynergy/deploy
  dependencies: []
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$DEV_SSH_PRIVATE_KEY" > ./key.file
    - chmod 400 ./key.file
    - ssh-add ./key.file
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - $DEV_SSH "cd livescore-web/ && git fetch && git pull && cd livescore/ && docker-compose up -d --build"
  only:
    - master
