version: "3.8"
services:
  nextjs:
    build: ./livescore
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      nextjs:
        condition: service_healthy
    ports:
      - 80:80
